### ISSUE TITLE
CPU utilization seems on par with busy waiting

### ISSUE THREAD

**Issue by Voultapher** [ogiroux/atomic_wait#1]
Tried using this to implement a simple barrier: https://github.com/Voultapher/atomic-wait-barrier

Trying multiple workloads and wake up timings, it seems that the current performance and behavior on linux is on par with busy waiting in terms of CPU utilization and total time spent, measured with `perf stat -d`.

Even replacing the waiting with an enormous 100ms sleep in the 64 barrier count scenario dramatically improves runtime performance and CPU utilization.

https://github.com/Voultapher/atomic-wait-barrier/blob/e64a2cede6801b4306d468fa7ebbb74505c69771/src/main.cpp#L24
```
atomic_wait(_count, local_count, std::memory_order_relaxed);
```

vs

```
std::this_thread::sleep_for(std::chrono::milliseconds{100});
```

System info:
Linux 5.1.4
Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
libc++ 8.0.1
clang 8.0.1

Maybe I'm using it wrong, would be great if you could shine some more light into this.

**Comment by ogiroux** [comment]
I'll look into it but I'm not totally surprised. There are a lot of different possible tuning corners and what barriers want is pretty different from what mutexes and ad-hoc flags want. I had not yet done any tuning of this implementation with barriers in scope, so it's "expected" that it would not be good at this time.

Parameters for what I will look into next:
* Changing the tuning choices to try to find a better center of mass among use cases.
* Using a barrier algorithm that segregates the phase polling and phase updates.
* And lastly, focus on the case when CPU hardware threads are not oversubscribed.

Hopefully I don't need to do too much platform-specific tuning, but we'll see.

Thanks for the feedback.

**Comment by ogiroux** [comment]
Oh lol, I had it checked in with `#define __NO_IDENT` so it was in fact just spinning.

I've added a barrier test, with a barrier that splits out the polled phase state. As you toggle the feature-detection on / off you'll see that the spinning version falls off a precipitous cliff under oversubscription. The non-spinning version keeps trucking along.

For such a short phase, that contains no computation of any kind, I expect the CPU utilization % to be fairly high. To some extent it's the feature working as intended -- keeping the CPU active so it can wake up quickly when the phases are short. As the phases get longer, the CPU utilization % should drop, saving power.

**Comment by Voultapher** [comment]
Alright just tried it and it seems fine.
